language: ruby

rvm:
    - 1.9.3
    - 2.0
    - 2.1

before_install:
    - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
    - bundle install

script:
    - bundle exec jekyll build

notifications:
    email: false

branches:
    only:
        - master
        - gh-pages
