#
# * Config
# * Stores static configuration and project info
# *
# * Copyright © SoftLayer, an IBM Company
# * Released under the MIT license
#

# 1. Spaces only, no tabs.
# 2. Wrap words in quotes wherever commas are used.
# 3. For options, use Y or N. Anything else will disable the option.


# ==============================
# Project
# ==============================

github:
    title:      Name of Your Website
    tagline:    Something Catchy to Describe your Website
    owner:      Name of Whoever Owns This
    license:    MIT

# ==============================
# Social
# ==============================

twitter:
    handle:     Your Twitter Name
    hashtags:   "separate,hashtags,with,commas"
    text:       "Check out our brand new website."
keywords:       "separate,keywords,with,commas"

# ==============================
# Options
# ==============================

analytics:
    enabled:    N
blur:
    enabled:    N
easing:
    enabled:    Y
indexing:
    enabled:    Y
version:
    enabled:    N

# ==============================
# Google Analytics
# ==============================

google:
    id:         UA-X

# ==============================
# Markdown
# ==============================

markdown:       redcarpet
redcarpet:
    extensions: ["autolink",
                 "fenced_code_blocks",
                 "highlight",
                 "lax_spacing",
                 "quote",
                 "smart",
                 "strikethrough",
                 "superscript",
                 "tables",
                 "underline",
                 "with_toc_data"]

# ==============================
# Server
# ==============================

permalink:      pretty
exclude:        [".gitignore",
                 "CONTRIBUTING.md",
                 "Gemfile"]
