#
# * Config
# * Stores static configuration and project info
# *
# * Copyright © Michael O'Rourke (@caleorourke)
# * Released under the MIT license
#

# (1) Spaces only, no tabs.
# (2) Wrap words in quotes wherever commas are used.
# (3) For options, use Y or N. Anything else will disable the option.


# ==============================
# Project
# ==============================

github:
    title:      Skim
    tagline:    A one-page boilerplate for publishing content on GitHub
    owner:      "Mielke Labs, LLC"
    license:    MIT

# ==============================
# Social
# ==============================

twitter:
    handle:     mielkelabs
    hashtags:   "css,boilerplate,github-pages"
    text:       "Try Skim, a one-page boilerplate for publishing content on GitHub."
keywords:       "boilerplate,caleorourke,css3,font awesome,github,github pages,html5,jekyll,jquery,liquid,markdown,normalize,one-page,pygments,python,redcarpet,ruby,skim,technical content"

# ==============================
# Options
# ==============================

index:
    enabled:    Y
scrolling:
    enabled:    Y
version:
    enabled:    Y

# ==============================
# Markdown
# ==============================

markdown:       redcarpet
redcarpet:
    extensions: ["autolink",
                 "fenced_code_blocks",
                 "highlight",
                 "lax_spacing",
                 "smart",
                 "strikethrough",
                 "superscript",
                 "tables",
                 "underline",
                 "with_toc_data"]

# ==============================
# Server
# ==============================

permalink:      pretty
exclude:        [".gitignore",
                 "Gemfile"]
