#
# * Config
# * Stores static configuration and project info
# *
# * Copyright © Michael O'Rourke
# * Code and documentation licensed under MIT
#

# (1) Spaces only, no tabs.
# (2) Wrap words in quotes wherever commas are used.
# (3) For options, use Y or N. Anything else will disable the option.


# ==============================
# Project
# ==============================

github:
    title:      Your Website
    tagline:    Something to Describe Your Website
    owner:      Whoever Owns This
    license:    Your License
keywords:       "separate,keywords,with,commas"

# ==============================
# Social
# ==============================

website:        http://www.yourcompany.com
twitter:
    handle:     Your Twitter Name
    hashtags:   "separate,hashtags,with,commas"
    text:       "Check out our project documentation on GitHub."


# ==============================
# Options
# ==============================

index:
    enabled:    Y
scrolling:
    enabled:    Y
version:
    enabled:    N

# ==============================
# Markdown
# ==============================

markdown:       redcarpet
redcarpet:
    extensions: ["autolink",
                 "fenced_code_blocks",
                 "highlight",
                 "lax_spacing",
                 "smart",
                 "strikethrough",
                 "superscript",
                 "tables",
                 "underline",
                 "with_toc_data"]

# ==============================
# Server
# ==============================

permalink:      pretty
exclude:        [".gitignore",
                 "Gemfile"]
